import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Inscriçao Play",
    description: "Inscriçao para participar nos campeonatos pagos",
    price: 0,
    image: "/images/Insc.png",
    category: "produtos",
    rarity: "lendario",
    inStock: true,
    featured: true,
  },
  {
    id: "prod-2",
    name: "Play Premium",
    description: "Adquira nosso Play Premium durante 30 dias",
    price: 10.00,
    image: "/images/Premium.png",
    category: "produtos",
    rarity: "lendario",
    inStock: true,
  },
  {
    id: "prod-3",
    name: "Shop",
    description: "Adquira nosso Shop durante 30 dias",
    price: 3.00,
    image: "/images/Shop.png",
    category: "produtos",
    rarity: "epico",
    inStock: true,
    featured: true,
  },
  {
    id: "prod-4",
    name: "Mulher",
    description: "Adquira nosso personagem mulher durante 30 dias",
    price: 2.50,
    image: "/images/Mulher.png",
    category: "produtos",
    rarity: "epico",
    inStock: true,
  },
  {
    id: "prod-5",
    name: "Tuning",
    description: "Adquira para tunar o seu carro",
    price: 4.50,
    image: "/images/Tuning.png",
    category: "produtos",
    rarity: "epico",
    inStock: true,
  },
  {
    id: "prod-6",
    name: "Token Troca",
    description: "Adquira para trocar itens no inventário",
    price: 1.50,
    image: "/images/Token.png",
    category: "produtos",
    rarity: "lendario",
    inStock: true,
  },
// Skins - MTAR (Class 1) - Épico e Raro
{
  id: "skin-mtar-azul",
  name: "MTAR AZUL",
  description: "MTAR com acabamento azul",
  price: 5.0,
  image: "/skins/mtarazul.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-mtar-red",
  name: "MTAR RED",
  description: "MTAR com acabamento vermelho",
  price: 5.0,
  image: "/skins/mtarred.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-mtar-love",
  name: "MTAR LOVE",
  description: "MTAR com design romântico",
  price: 5.0,
  image: "/skins/love.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-mtar-mickey",
  name: "MTAR MICKEY",
  description: "MTAR com temática Mickey",
  price: 5.0,
  image: "/skins/weapon_mtarmickey.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "epico",
  inStock: true,
  featured: true,
},
{
  id: "skin-mtar-roxa",
  name: "MTAR ROXA",
  description: "MTAR com acabamento roxo",
  price: 5.0,
  image: "/skins/weapon_mtarroxa.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "epico",
  inStock: true,
},
{
  id: "skin-mtar-brinquedo",
  name: "BRINQUEDO",
  description: "MTAR com visual de brinquedo",
  price: 5.0,
  image: "/skins/brinquedo.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-mtar-gelo",
  name: "MTAR GELO",
  description: "MTAR com padrão de gelo congelado",
  price: 5.0,
  image: "/skins/gelo.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-mtar-under",
  name: "MTAR UNDERGROUND",
  description: "MTAR com tema underground",
  price: 5.0,
  image: "/skins/mtarund.png",
  category: "skins",
  subcategory: "mtar",
  rarity: "epico",
  inStock: true,
},

// Skins - G3 e M4 - Mítico e Lendário
{
  id: "skin-m4",
  name: "M4 RED",
  description: "M4 com acabamento vermelho",
  price: 10.0,
  image: "/skins/m4.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-goat-azul",
  name: "G3 GOAT AZUL",
  description: "G3 GOAT com acabamento azul",
  price: 10.0,
  image: "/skins/goat.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
  featured: true,
},
{
  id: "skin-chefao",
  name: "G3 CHEFAO",
  description: "G3 exclusiva do chefão",
  price: 10.0,
  image: "/skins/chefao.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-hoho",
  name: "G3 PISCA PISCA",
  description: "G3 com design pisca pisca",
  price: 10.0,
  image: "/skins/hoho.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-m4-natal",
  name: "M4 NATAL",
  description: "M4 temática de Natal",
  price: 10.0,
  image: "/skins/m4natal.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-esqueleto",
  name: "G3 ESQUELETO",
  description: "G3 com padrão de esqueleto",
  price: 10.0,
  image: "/skins/esqueleto.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-metropole",
  name: "G3 METROPOLE",
  description: "G3 com design metropolitano",
  price: 10.0,
  image: "/skins/arma.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
  featured: true,
},
{
  id: "skin-alfa",
  name: "G3 ALFA",
  description: "G3 Alfa",
  price: 10.0,
  image: "/skins/alfa.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-branca",
  name: "M4 GELO",
  description: "M4 com acabamento branco gelado",
  price: 10.0,
  image: "/skins/branca.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-fantasma",
  name: "G3 FANTASMA",
  description: "G3 com tema fantasmagórico",
  price: 10.0,
  image: "/skins/fantasma.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-goat-prata",
  name: "G3 GOAT PRATA",
  description: "G3 GOAT com acabamento prateado",
  price: 10.0,
  image: "/skins/goatprata.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
  featured: true,
},
{
  id: "skin-goat-rosa",
  name: "G3 GOAT ROSA",
  description: "G3 GOAT com acabamento rosa",
  price: 10.0,
  image: "/skins/goatrosa.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-goat-roxa",
  name: "G3 GOAT ROXA",
  description: "G3 GOAT com acabamento roxo",
  price: 10.0,
  image: "/skins/goatroxa.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},

{
  id: "skin-goat-green",
  name: "G3 GOAT VERDE",
  description: "G3 GOAT com acabamento verde",
  price: 10.0,
  image: "/skins/goatverde.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-psycho",
  name: "G3 PSYCHO",
  description: "G3 com design psicótico",
  price: 10.0,
  image: "/skins/psycho.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-rosa",
  name: "M4 ROSA",
  description: "M4 com acabamento rosa",
  price: 10.0,
  image: "/skins/rosa.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-tanjiro",
  name: "G3 TANJIRO",
  description: "G3 inspirada em Tanjiro",
  price: 10.0,
  image: "/skins/tanjiro.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-g3gel",
  name: "G3 GEL",
  description: "G3 com acabamento gel",
  price: 10.0,
  image: "/skins/weapon_g3gel.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-g3mengao",
  name: "G3 MENGAO",
  description: "G3 temática Flamengo",
  price: 10.0,
  image: "/skins/weapon_g3mengao.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-g3sublime",
  name: "G3 SUBLIME",
  description: "G3 com design sublime",
  price: 10.0,
  image: "/skins/weapon_g3sublime.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-m4wall",
  name: "M4 WALL",
  description: "M4 com design wall",
  price: 10.0,
  image: "/skins/weapon_m4wall.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-ferro",
  name: "FERRO",
  description: "G3 com acabamento de ferro",
  price: 10.0,
  image: "/skins/ferro.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-yingyang",
  name: "G3 YINGYANG",
  description: "G3 com padrão Yin Yang",
  price: 10.0,
  image: "/skins/yingyang.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-namorados",
  name: "NAMORADOS",
  description: "G3 especial Dia dos Namorados",
  price: 10.0,
  image: "/skins/namorados.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-oni",
  name: "M4 WHITEFIRE",
  description: "M4 temática Whitefire",
  price: 10.0,
  image: "/skins/oni.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
  featured: true,
},
{
  id: "skin-vegas",
  name: "G3 VEGAS",
  description: "G3 temática Las Vegas",
  price: 10.0,
  image: "/skins/vegas.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-purple",
  name: "PURPLE",
  description: "G3 roxa",
  price: 10.0,
  image: "/skins/purple.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-sonic",
  name: "SONIC",
  description: "G3 temática Sonic",
  price: 10.0,
  image: "/skins/sonic.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-under",
  name: "UNDER",
  description: "G3 Underground",
  price: 10.0,
  image: "/skins/under.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-special",
  name: "SPECIAL",
  description: "G3 Especial",
  price: 10.0,
  image: "/skins/special.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-treno",
  name: "TRENO",
  description: "G3 Treno",
  price: 10.0,
  image: "/skins/treno.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-sakura",
  name: "SAKURA",
  description: "G3 com padrão de flores de cerejeira",
  price: 10.0,
  image: "/skins/sakura.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-g3rgx",
  name: "G3 RGX",
  description: "G3 com design RGX",
  price: 10.0,
  image: "/skins/g3rgx.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
  featured: true,
},
{
  id: "skin-divas",
  name: "DIVAS",
  description: "G3 temática Divas",
  price: 10.0,
  image: "/skins/divas.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},
{
  id: "skin-parafalroxa",
  name: "PARAFAL ROXA",
  description: "Parafal com acabamento roxo",
  price: 10.0,
  image: "/skins/parafalroxa.png",
  category: "skins",
  subcategory: "g3",
  rarity: "lendario",
  inStock: true,
},

// Skins - Facas - 15€
{
  id: "skin-faca-autotronic",
  name: "FACA AUTOTRONIC",
  description: "Faca com design autotronic",
  price: 15.0,
  image: "/skins/default.png",
  category: "skins",
  subcategory: "facas",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-faca-borboleta",
  name: "Borboleta",
  description: "Faca borboleta clássica",
  price: 15.0,
  image: "/skins/default.png",
  category: "skins",
  subcategory: "facas",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-faca-lore",
  name: "Lore",
  description: "Faca com padrão Lore",
  price: 15.0,
  image: "/skins/default.png",
  category: "skins",
  subcategory: "facas",
  rarity: "raro",
  inStock: true,
},
{
  id: "skin-faca-oncia",
  name: "FACA ONCIA",
  description: "Faca com padrão de onça",
  price: 15.0,
  image: "/skins/oncia.png",
  category: "skins",
  subcategory: "facas",
  rarity: "raro",
  inStock: true,
},
  // Caixas
  {
    id: "box-1",
    name: "Caixa Play Cup",
    description: "Caixa com todas as nossas Skins do Servidor",
    price: 5.00,
    image: "/images/box.png",
    category: "caixas",
    rarity: "lendario",
    inStock: true,
  },

  // Veículos
  {
    id: "vei-1",
    name: "Kuruma Personalizado",
    description: "Kuruma Personalziado com a Logotipo da sua Tropa e do seu jeito",
    price: 15,
    image: "/images/Carro.png",
    category: "veiculos",
    rarity: "lendario",
    inStock: true,
    featured: true,
  },
]

export const getProductById = (id: string) => products.find((p) => p.id === id)
export const getProductsByCategory = (category: Product["category"]) => products.filter((p) => p.category === category)
export const getFeaturedProducts = () => products.filter((p) => p.featured)
